[pytest]
testpaths = common/tests client/tests server/tests
asyncio_mode = auto
filterwarnings =
    error::DeprecationWarning:server.*
    error::DeprecationWarning:client.*
    error::DeprecationWarning:common.*
